parameters:
    app.upload_directory: '%kernel.project_dir%/public/uploads'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeService:
        arguments:
            $secretKey: '%stripe.secret_key%'

    App\Service\FileUploadService:
        arguments:
            $uploadDirectory: '%app.upload_directory%'

