nelmio_api_doc:
    documentation:
        info:
            title: BricoMalin API
            description: API REST pour l'application BricoMalin
            version: 1.0.0
        servers:
            - url: http://localhost:8000
              description: Serveur de d√©veloppement
    areas:
        path_patterns:
            - ^/api(?!/doc)
        host_patterns:
            - ^api\.
            - ^localhost

